### ISSUE TITLE
Run tournaments

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/revisiting-axelrod-second#2]
- [x] Get TourExec on raven (our cluster)
- [x] Write a script to write pbs scripts (for each and every tournament we want)
- [x] Write a script to run tournaments (aiming for high reps so will use same data generation as for https://github.com/Axelrod-Python/ml-paper/blob/master/src/main.py)
- [x] Run tournaments.

**Comment by marcharper** [comment]
[Earlier thread](https://github.com/Axelrod-Python/axelrod-fortran/issues/23)

**Comment by marcharper** [comment]
Various ideas:

* Axelrod's tournament 1000x-10000x with the five choices of tournament length and a proper probabilistic ending tournament
* Rerun with all (short run time?) axelrod library strategies. First run at 1000x showed that our ML strategies still faired well
* Same with noise (+DBS)
* Our trained strategies do not seem to win when added individually to the fortran collection [verify this]. Assuming this is true, I suspect it's because the Fortran strategies are all too "nice", and the ML strategies may be overfit on some meta-parameters of their training strategy space
* Train memory one (stochastic and deterministic) and other ML strategies with fortran strategies at the training pool. Are the results similar?

**Comment by drvinceknight** [comment]
> Our trained strategies do not seem to win when added individually to the fortran collection [verify this]. Assuming this is true, I suspect it's because the Fortran strategies are all too "nice", and the ML strategies may be overfit on some meta-parameters of their training strategy space

There might be other strategies in the library that do do well (and do poorly in ours), I think your suggestion of running the tournament with a single addition of a every strategy in axelrod is definitely worth doing.

**Comment by marcharper** [comment]
Let's also remember to:
* [ ] rerun the examples repository
* [ ] rerun the fingerprints

**Comment by drvinceknight** [comment]
I'll put something together on the fingerprints repo to include `axelrod-fortran` strategies too and get those running.

**Comment by drvinceknight** [comment]
Closing this: am rerunning the fingerprints (this takes a loooong time) and will open an issue on the examples repo.

For this actual repo I am running various tournaments and updating results on the `revisit` branch. Once they're done I will communicate this.
